/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk_laundry; 

import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class laundry_apk extends javax.swing.JFrame {

    /**
     * Creates new form laundry_apk
     */
    public laundry_apk() {
        initComponents();
    }
         public int Total_Harga;
    
    public void reset(){
        pilihan.setSelectedItem("Pilihan");
         txt_harga.setText("");
          txt_berat.setText("");
           txt_totalhar.setText("");
            txt_bayar.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pilihan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        transaksi = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        txt_totalhar = new javax.swing.JTextField();
        txt_berat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        txt_bayar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Laundry Cuy");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel2.setText("Bayar: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        pilihan.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan", "Cuci Bersih", "Cuci Kering", "Cuci Setrika" }));
        pilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanActionPerformed(evt);
            }
        });
        jPanel1.add(pilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 240, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel3.setText("Jenis: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel4.setText("Berat: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel5.setText("Harga: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        jLabel6.setText("Total Harga: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        transaksi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        transaksi.setText("Transaksi\n");
        transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksiActionPerformed(evt);
            }
        });
        jPanel1.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        batal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 130, -1));
        jPanel1.add(txt_totalhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 240, 40));

        txt_berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_beratKeyReleased(evt);
            }
        });
        jPanel1.add(txt_berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 230, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kg");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        txt_harga.setEditable(false);
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 240, -1));
        jPanel1.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 240, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 560);

        setBounds(0, 0, 580, 618);
    }// </editor-fold>//GEN-END:initComponents

    private void transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksiActionPerformed
        if (txt_berat.getText().isEmpty() || txt_harga.getText().isEmpty() || txt_totalhar.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Data harus diisi");
    } else {
        try {
            double bayar = Double.parseDouble(txt_bayar.getText());
            double harga = Double.parseDouble(txt_harga.getText());
            double berat = Double.parseDouble(txt_berat.getText());
            double totalHarga = harga * berat;
            double kembalian = bayar - totalHarga;

            JOptionPane.showMessageDialog(null, "Kembalian Anda :\n" + kembalian);
            reset();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Masukkan angka yang valid.");
        }
         }
    }//GEN-LAST:event_transaksiActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        reset();
    }//GEN-LAST:event_batalActionPerformed

    private void pilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanActionPerformed
         if (pilihan.getSelectedItem().equals("Pilihan")){
            txt_harga.setText("0");
        }else if(pilihan.getSelectedItem().equals("Cuci Bersih")){
            txt_harga.setText("3000");
        }else if(pilihan.getSelectedItem().equals("Cuci Kering")){
            txt_harga.setText("4000");
        }else if(pilihan.getSelectedItem().equals("Cuci Setrika")){
            txt_harga.setText("5000");
        }
    }//GEN-LAST:event_pilihanActionPerformed

    private void txt_beratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_beratKeyReleased
                                 
    if (txt_berat.getText().isEmpty()) {
        txt_totalhar.setText("0");
    } else {
        try {
            int harga = Integer.parseInt(txt_harga.getText());
            float berat = Float.parseFloat(txt_berat.getText());
            Total_Harga = (int) (harga * berat);
            txt_totalhar.setText(String.valueOf(Total_Harga));
        } catch (NumberFormatException e) {
            txt_totalhar.setText("0");
        }
       }
    }//GEN-LAST:event_txt_beratKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laundry_apk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laundry_apk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laundry_apk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laundry_apk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laundry_apk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> pilihan;
    private javax.swing.JButton transaksi;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_totalhar;
    // End of variables declaration//GEN-END:variables
}
